### ISSUE TITLE
Generalize webhook format

### ISSUE THREAD

**Issue by yukukotani** [kory33/redmine_discord#7]
Make user able to configure a template of webhook format which includes a placeholder of values such as username or avatar's URL.

It would be useful to provide default templates for Slack and Discord.

**Comment by yukukotani** [comment]
I will work on this issue about a week later if no one does and there are no problem.

**Comment by kory33** [comment]
+1 to this feature;

Username and avatar URL are already configurable from the plugin settings, but it would indeed be nice if a user can configure templates for dispatched json objects.

Just for your information, current implementation requires a lot of rewrite to achieve this kind of flexibility. Structures of dispatched objects are nearly hard-coded in accordance with Discord's embed API.

I will be welcoming a Pull Request for the changes,

**Comment by yukukotani** [comment]
I think it is smarter to rewrite current code than write from scratch.

Thank you for your reception.

**Comment by kory33** [comment]
Right, another thing would be that Discord's embed API does not accept an empty field, i.e. you can never send a field without a value in it. This hinders a lot in implementing this feature, and even if this is possible, the user interface to manage the configuration would be very intricate.

But anyways, thank you for your suggestion!
